<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AFK4.Shared.Contracts\AFK4.Shared.Contracts.csproj" />
    <ProjectReference Include="..\AFK4.Localization\AFK4.Localization.csproj" />
    <ProjectReference Include="..\AFK4.Localization.Wpf\AFK4.Localization.Wpf.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
