// Backend permission-name catalog. Split out from operatorPermissions.ts so it has no
// dependencies of its own — management/managementNav.ts needs it at module-load time (its
// destinations array is built eagerly), and operatorPermissions.ts imports managementNav's
// output back (workspacePermissionRules.management). Importing permissionNames from
// operatorPermissions.ts in managementNav.ts would create an import cycle that throws
// "Cannot access 'permissionNames' before initialization" at module load.
export const permissionNames = {
  viewFloorMap: 'organization.floor_map.view',
  startSession: 'organization.sessions.start',
  extendSession: 'organization.sessions.extend',
  transferSession: 'organization.sessions.transfer',
  endSession: 'organization.sessions.end',
  viewSessions: 'organization.sessions.view',
  viewPlayers: 'organization.players.view',
  createPlayerAccount: 'organization.players.create',
  viewBilling: 'organization.billing.view',
  topUpWallet: 'organization.billing.wallet.top_up',
  payDebt: 'organization.billing.debt.pay',
  viewPackages: 'organization.packages.view',
  managePackages: 'organization.packages.manage',
  purchasePackage: 'organization.packages.purchase',
  viewShift: 'organization.shifts.view',
  openShift: 'organization.shifts.open',
  closeShift: 'organization.shifts.close',
  manageShiftCash: 'organization.shifts.cash.manage',
  viewReports: 'organization.reports.view',
  viewReservations: 'organization.reservations.view',
  manageReservations: 'organization.reservations.manage',
  createPosSale: 'organization.pos.sales.create',
  payPosSale: 'organization.pos.sales.pay',
  refundPosSale: 'organization.pos.sales.refund',
  voidPosSale: 'organization.pos.sales.void',
  viewInventory: 'organization.inventory.view',
  manageInventoryStock: 'organization.inventory.stock.manage',
  managePosCatalog: 'organization.pos.catalog.manage',
  viewReceipt: 'organization.receipts.view',
  viewDiagnostics: 'organization.diagnostics.view',
  manageBranchStaff: 'organization.identity.branch_staff.manage',
  manageRoles: 'organization.identity.roles.manage',
  manageLayout: 'organization.layout.manage',
  manageBranchSettings: 'organization.branches.settings.manage',
  createDeviceEnrollmentCode: 'organization.devices.enrollment_codes.create',
  assignDeviceSeat: 'organization.devices.seat_assignment.assign',
  viewDeviceDetail: 'organization.devices.detail.view',
  dispatchDeviceCommand: 'organization.devices.commands.dispatch',
  rotateDeviceCredential: 'organization.devices.credentials.rotate',
  revokeDeviceCredential: 'organization.devices.credentials.revoke',
  manageTariffs: 'organization.tariffs.manage',
  viewTariffs: 'organization.tariffs.view',
  viewUpdateStatus: 'organization.updates.status.view',
  manageUpdatePackages: 'organization.updates.packages.manage',
  manageUpdateRollouts: 'organization.updates.rollouts.manage',
  viewDeviceCommandStatus: 'organization.devices.commands.status.view',
  viewAudit: 'organization.audit.view',
  viewOrganizationAudit: 'organization.audit.organization.view',
  viewSubscription: 'organization.billing.subscription.view',
  installDevice: 'organization.devices.install',
  viewBranches: 'organization.branches.view',
  approveMoneyAction: 'organization.billing.money_action.approve',
  manualCorrection: 'organization.billing.manual_correction',
  refundLedgerEntry: 'organization.billing.refund',
  managePaymentGateways: 'organization.payments.gateways.manage',
  manageLoyaltySettings: 'organization.loyalty.settings.manage',
  manageNews: 'organization.news.manage'
} as const;
