// Backend permission-name catalog. Split out from operatorPermissions.ts so it has no
// dependencies of its own — management/managementNav.ts needs it at module-load time (its
// destinations array is built eagerly), and operatorPermissions.ts imports managementNav's
// output back (workspacePermissionRules.management). Importing permissionNames from
// operatorPermissions.ts in managementNav.ts would create an import cycle that throws
// "Cannot access 'permissionNames' before initialization" at module load.
export const permissionNames = {
  viewFloorMap: 'floor_map.view',
  startSession: 'sessions.start',
  extendSession: 'sessions.extend',
  transferSession: 'sessions.transfer',
  endSession: 'sessions.end',
  viewSessions: 'sessions.view',
  viewPlayers: 'players.view',
  createPlayerAccount: 'players.create',
  viewBilling: 'billing.view',
  topUpWallet: 'billing.wallet.top_up',
  payDebt: 'billing.debt.pay',
  viewPackages: 'packages.view',
  managePackages: 'packages.manage',
  purchasePackage: 'packages.purchase',
  viewShift: 'shifts.view',
  openShift: 'shifts.open',
  closeShift: 'shifts.close',
  manageShiftCash: 'shifts.cash.manage',
  viewReports: 'reports.view',
  viewReservations: 'reservations.view',
  manageReservations: 'reservations.manage',
  createPosSale: 'pos.sales.create',
  payPosSale: 'pos.sales.pay',
  refundPosSale: 'pos.sales.refund',
  voidPosSale: 'pos.sales.void',
  viewInventory: 'inventory.view',
  manageInventoryStock: 'inventory.stock.manage',
  managePosCatalog: 'pos.catalog.manage',
  viewReceipt: 'receipts.view',
  viewDiagnostics: 'diagnostics.view',
  manageBranchStaff: 'identity.branch_staff.manage',
  manageRoles: 'identity.roles.manage',
  manageLayout: 'layout.manage',
  manageBranchSettings: 'branches.settings.manage',
  createDeviceEnrollmentCode: 'devices.enrollment_codes.create',
  assignDeviceSeat: 'devices.seat_assignment.assign',
  viewDeviceDetail: 'devices.detail.view',
  dispatchDeviceCommand: 'devices.commands.dispatch',
  rotateDeviceCredential: 'devices.credentials.rotate',
  revokeDeviceCredential: 'devices.credentials.revoke',
  manageTariffs: 'tariffs.manage',
  viewTariffs: 'tariffs.view',
  viewUpdateStatus: 'updates.status.view',
  manageUpdatePackages: 'updates.packages.manage',
  manageUpdateRollouts: 'updates.rollouts.manage',
  viewDeviceCommandStatus: 'devices.commands.status.view',
  viewAudit: 'audit.view',
  viewSubscription: 'billing.subscription.view',
  installDevice: 'devices.install',
  viewBranches: 'branches.view',
  approveMoneyAction: 'billing.money_action.approve',
  manualCorrection: 'billing.manual_correction',
  refundLedgerEntry: 'billing.refund',
  managePaymentGateways: 'payments.gateways.manage',
  manageLoyaltySettings: 'loyalty.settings.manage',
  manageNews: 'news.manage'
} as const;
