using AFK4.Shared.Contracts.Identity;

namespace AFK4.Platform.Api.Identity;

public static class PermissionCatalog
{
    private static readonly IReadOnlyDictionary<string, IReadOnlySet<string>> RolePermissions =
        new Dictionary<string, IReadOnlySet<string>>(StringComparer.OrdinalIgnoreCase)
        {
            [StaffRoleNames.Owner] = new HashSet<string>
            {
                StaffPermissionNames.CreateDeviceEnrollmentCode,
                StaffPermissionNames.DispatchDeviceCommand,
                StaffPermissionNames.ViewDeviceCommandStatus,
                StaffPermissionNames.RotateDeviceCredential,
                StaffPermissionNames.RevokeDeviceCredential,
                StaffPermissionNames.AssignDeviceSeat,
                StaffPermissionNames.ViewDeviceDetail,
                StaffPermissionNames.InstallDevice,
                StaffPermissionNames.ViewFloorMap,
                StaffPermissionNames.ManageLayout,
                StaffPermissionNames.StartSession,
                StaffPermissionNames.ExtendSession,
                StaffPermissionNames.TransferSession,
                StaffPermissionNames.EndSession,
                StaffPermissionNames.ViewSession,
                StaffPermissionNames.CreatePlayerAccount,
                StaffPermissionNames.ViewPlayers,
                StaffPermissionNames.ViewBilling,
                StaffPermissionNames.TopUpWallet,
                StaffPermissionNames.RefundLedgerEntry,
                StaffPermissionNames.ManualLedgerCorrection,
                StaffPermissionNames.PayDebt,
                StaffPermissionNames.ApproveMoneyAction,
                StaffPermissionNames.ViewSubscription,
                StaffPermissionNames.ManageTariffs,
                StaffPermissionNames.ViewTariffs,
                StaffPermissionNames.ManagePackages,
                StaffPermissionNames.ViewPackages,
                StaffPermissionNames.PurchasePackage,
                StaffPermissionNames.OpenShift,
                StaffPermissionNames.CloseShift,
                StaffPermissionNames.ViewShift,
                StaffPermissionNames.ManageShiftCash,
                StaffPermissionNames.ViewReports,
                StaffPermissionNames.ViewReservations,
                StaffPermissionNames.ManageReservations,
                StaffPermissionNames.ManagePosCatalog,
                StaffPermissionNames.ManageShopOrders,
                StaffPermissionNames.CreatePosSale,
                StaffPermissionNames.PayPosSale,
                StaffPermissionNames.RefundPosSale,
                StaffPermissionNames.VoidPosSale,
                StaffPermissionNames.ManageInventoryStock,
                StaffPermissionNames.ViewInventory,
                StaffPermissionNames.ViewReceipt,
                StaffPermissionNames.ManageUpdatePackages,
                StaffPermissionNames.ManageUpdateRollouts,
                StaffPermissionNames.ViewUpdateStatus,
                StaffPermissionNames.ViewDiagnostics,
                StaffPermissionNames.ManageBranchStaff,
                StaffPermissionNames.ManageRoles,
                StaffPermissionNames.ViewAudit,
                StaffPermissionNames.ManageOwnerCode,
                StaffPermissionNames.ManageBranchSettings,
                StaffPermissionNames.ManagePaymentGateways
            },
            [StaffRoleNames.BranchManager] = new HashSet<string>
            {
                StaffPermissionNames.CreateDeviceEnrollmentCode,
                StaffPermissionNames.DispatchDeviceCommand,
                StaffPermissionNames.ViewDeviceCommandStatus,
                StaffPermissionNames.RotateDeviceCredential,
                StaffPermissionNames.RevokeDeviceCredential,
                StaffPermissionNames.AssignDeviceSeat,
                StaffPermissionNames.ViewDeviceDetail,
                StaffPermissionNames.InstallDevice,
                StaffPermissionNames.ViewFloorMap,
                StaffPermissionNames.ManageLayout,
                StaffPermissionNames.StartSession,
                StaffPermissionNames.ExtendSession,
                StaffPermissionNames.TransferSession,
                StaffPermissionNames.EndSession,
                StaffPermissionNames.ViewSession,
                StaffPermissionNames.CreatePlayerAccount,
                StaffPermissionNames.ViewPlayers,
                StaffPermissionNames.ViewBilling,
                StaffPermissionNames.TopUpWallet,
                StaffPermissionNames.RefundLedgerEntry,
                StaffPermissionNames.ManualLedgerCorrection,
                StaffPermissionNames.PayDebt,
                StaffPermissionNames.ApproveMoneyAction,
                StaffPermissionNames.ManageTariffs,
                StaffPermissionNames.ViewTariffs,
                StaffPermissionNames.ManagePackages,
                StaffPermissionNames.ViewPackages,
                StaffPermissionNames.PurchasePackage,
                StaffPermissionNames.OpenShift,
                StaffPermissionNames.CloseShift,
                StaffPermissionNames.ViewShift,
                StaffPermissionNames.ManageShiftCash,
                StaffPermissionNames.ViewReports,
                StaffPermissionNames.ViewReservations,
                StaffPermissionNames.ManageReservations,
                StaffPermissionNames.ManagePosCatalog,
                StaffPermissionNames.ManageShopOrders,
                StaffPermissionNames.CreatePosSale,
                StaffPermissionNames.PayPosSale,
                StaffPermissionNames.RefundPosSale,
                StaffPermissionNames.VoidPosSale,
                StaffPermissionNames.ManageInventoryStock,
                StaffPermissionNames.ViewInventory,
                StaffPermissionNames.ViewReceipt,
                StaffPermissionNames.ManageUpdatePackages,
                StaffPermissionNames.ManageUpdateRollouts,
                StaffPermissionNames.ViewUpdateStatus,
                StaffPermissionNames.ViewDiagnostics,
                StaffPermissionNames.ManageBranchStaff,
                StaffPermissionNames.ViewAudit,
                StaffPermissionNames.ManageBranchSettings
            },
            [StaffRoleNames.ShiftSupervisor] = new HashSet<string>
            {
                StaffPermissionNames.ViewDeviceCommandStatus,
                StaffPermissionNames.ViewDeviceDetail,
                StaffPermissionNames.ViewFloorMap,
                StaffPermissionNames.StartSession,
                StaffPermissionNames.ExtendSession,
                StaffPermissionNames.TransferSession,
                StaffPermissionNames.EndSession,
                StaffPermissionNames.ViewSession,
                StaffPermissionNames.CreatePlayerAccount,
                StaffPermissionNames.ViewPlayers,
                StaffPermissionNames.ViewBilling,
                StaffPermissionNames.TopUpWallet,
                StaffPermissionNames.RefundLedgerEntry,
                StaffPermissionNames.ManualLedgerCorrection,
                StaffPermissionNames.PayDebt,
                StaffPermissionNames.ViewTariffs,
                StaffPermissionNames.ViewPackages,
                StaffPermissionNames.PurchasePackage,
                StaffPermissionNames.OpenShift,
                StaffPermissionNames.CloseShift,
                StaffPermissionNames.ViewShift,
                StaffPermissionNames.ManageShiftCash,
                StaffPermissionNames.ViewReports,
                StaffPermissionNames.ViewReservations,
                StaffPermissionNames.ManageReservations,
                StaffPermissionNames.CreatePosSale,
                StaffPermissionNames.PayPosSale,
                StaffPermissionNames.RefundPosSale,
                StaffPermissionNames.VoidPosSale,
                StaffPermissionNames.ViewInventory,
                StaffPermissionNames.ViewReceipt,
                StaffPermissionNames.ViewUpdateStatus,
                StaffPermissionNames.ViewDiagnostics,
                StaffPermissionNames.ViewAudit
            },
            [StaffRoleNames.CashierOperator] = new HashSet<string>
            {
                StaffPermissionNames.ViewFloorMap,
                StaffPermissionNames.StartSession,
                StaffPermissionNames.ExtendSession,
                StaffPermissionNames.TransferSession,
                StaffPermissionNames.EndSession,
                StaffPermissionNames.ViewSession,
                StaffPermissionNames.CreatePlayerAccount,
                StaffPermissionNames.ViewPlayers,
                StaffPermissionNames.ViewBilling,
                StaffPermissionNames.TopUpWallet,
                StaffPermissionNames.PayDebt,
                StaffPermissionNames.ViewTariffs,
                StaffPermissionNames.ViewPackages,
                StaffPermissionNames.PurchasePackage,
                StaffPermissionNames.OpenShift,
                StaffPermissionNames.ViewShift,
                StaffPermissionNames.ViewReservations,
                StaffPermissionNames.ManageReservations,
                StaffPermissionNames.CreatePosSale,
                StaffPermissionNames.PayPosSale,
                StaffPermissionNames.ViewReceipt
            },
            [StaffRoleNames.Technician] = new HashSet<string>
            {
                StaffPermissionNames.CreateDeviceEnrollmentCode,
                StaffPermissionNames.DispatchDeviceCommand,
                StaffPermissionNames.ViewDeviceCommandStatus,
                StaffPermissionNames.RotateDeviceCredential,
                StaffPermissionNames.RevokeDeviceCredential,
                StaffPermissionNames.AssignDeviceSeat,
                StaffPermissionNames.ViewDeviceDetail,
                StaffPermissionNames.InstallDevice,
                StaffPermissionNames.ViewFloorMap,
                StaffPermissionNames.ViewInventory,
                StaffPermissionNames.ManageUpdatePackages,
                StaffPermissionNames.ManageUpdateRollouts,
                StaffPermissionNames.ViewUpdateStatus,
                StaffPermissionNames.ViewDiagnostics
            },
            [StaffRoleNames.AccountantAuditor] = new HashSet<string>
            {
                StaffPermissionNames.ViewSession,
                StaffPermissionNames.ViewPlayers,
                StaffPermissionNames.ViewBilling,
                StaffPermissionNames.ViewTariffs,
                StaffPermissionNames.ViewPackages,
                StaffPermissionNames.ViewShift,
                StaffPermissionNames.ViewReports,
                StaffPermissionNames.ViewReservations,
                StaffPermissionNames.ViewInventory,
                StaffPermissionNames.ViewReceipt,
                StaffPermissionNames.ViewUpdateStatus,
                StaffPermissionNames.ViewDiagnostics,
                StaffPermissionNames.ViewAudit
            }
        };

    public static IReadOnlySet<string> GetPermissions(IEnumerable<string> roleNames)
    {
        var permissions = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var roleName in roleNames)
        {
            if (!RolePermissions.TryGetValue(roleName, out var rolePermissions))
            {
                continue;
            }

            permissions.UnionWith(rolePermissions);
        }

        return permissions;
    }
}
