namespace AFK4.Update.Publisher;

public sealed record UpdatePackagePublishOptions(
    Guid OrganizationId,
    string Component,
    string Version,
    string Channel,
    string ArtifactPath,
    string? HostingRoot,
    Uri? PublicBaseUri,
    string? SigningPrivateKeyPemPath,
    string ReleaseNotes,
    string? PublishedFileName = null,
    string? RequestJsonOutputPath = null,
    string ArtifactStoreKind = UpdateArtifactStoreKindNames.FileSystem,
    Uri? ArtifactUploadUri = null,
    Uri? PublicArtifactUri = null,
    string? SigningPrivateKeyPemEnvironmentVariable = null,
    Uri? S3Endpoint = null,
    string? S3Bucket = null,
    string? S3KeyPrefix = null,
    string? S3AccessKeyEnvironmentVariable = null,
    string? S3SecretKeyEnvironmentVariable = null,
    string S3Region = "us-east-1",
    string? S3StableAliasObjectKey = null);
